### ISSUE TITLE
 Invalid plugin config file GodotAppodeal.gdap

### ISSUE THREAD

**Issue by CozmoGames** [PoqXert/godot-appodeal-android-plugin#2]
not sure what this is please help

**Comment by CozmoGames** [comment]
also this too:  "Failed to get modified time for: C:/Users/Anthony Chen/Desktop/godot projects/app/android/plugins/GodotAppodeal.1.0.0.release.aar"

**Comment by PoqXert** [comment]
Try re-download files (or modify it).
https://godotforums.org/discussion/23162/a-lot-of-errors

**Comment by CozmoGames** [comment]
ok it doesnt show the issue now but now i cant export for android. Heres the gradle build thing

Task :preBuild UP-TO-DATE
Task :preDebugBuild UP-TO-DATE
Task :compileDebugAidl NO-SOURCE
Task :checkDebugManifest UP-TO-DATE
Task :compileDebugRenderscript NO-SOURCE
Task :generateDebugBuildConfig UP-TO-DATE
Task :javaPreCompileDebug UP-TO-DATE
Task :mainApkListPersistenceDebug UP-TO-DATE
Task :generateDebugResValues UP-TO-DATE
Task :generateDebugResources UP-TO-DATE
Task :mergeDebugResources UP-TO-DATE
Task :createDebugCompatibleScreenManifests UP-TO-DATE

Task :processDebugManifest FAILED

C:\Users\Me\Desktop\godot projects\app\android\build\AndroidManifest.xml:30:18-67 Error:
Attribute application@label value=(@string/godot_project_name_string) from AndroidManifest.xml:30:18-67
is also present at [com.ironsource.sdk:mediationsdk:6.16.0] AndroidManifest.xml:16:9-41 value=(@string/app_name).
Suggestion: add 'tools:replace="android:label"' to element at AndroidManifest.xml:30:5-70:19 to override.

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':processDebugManifest'.

Manifest merger failed : Attribute application@label value=(@string/godot_project_name_string) from AndroidManifest.xml:30:18-67

is also present at [com.ironsource.sdk:mediationsdk:6.16.0] AndroidManifest.xml:16:9-41 value=(@string/app_name).
Suggestion: add 'tools:replace="android:label"' to element at AndroidManifest.xml:30:5-70:19 to override.

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUILD FAILED in 5s
8 actionable tasks: 1 executed, 7 up-to-date

Exit Code: 1

**Comment by PoqXert** [comment]
Add attribute `tools:replace` with value `android:label` (and other conflicts) to `application` element in `<ProjectFolder>/android/build/AndroidManifest.xml`
```xml
<application tools:replace="android:allowBackup,android:label">
...
</application>
```

**Comment by CozmoGames** [comment]
ok i did that but i still cant build.

Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':processReleaseResources'.
> Could not create task ':mainApkListPersistenceRelease'.
   > org.xml.sax.SAXParseException; systemId: file:/C:/Users/Anthony%20Chen/Desktop/godot%20projects/app/android/build/AndroidManifest.xml; lineNumber: 30; columnNumber: 62; Element type "application" must be followed by either attribute specifications, ">" or "/>".

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s

Exit Code: 1

**Comment by PoqXert** [comment]
I don't know what you have in `AndroidManifest.xml`. But you have incorrect `application` element. (Missed `"`, `>` or `/>`)

Read error, find it in your file, fix.

**Comment by CozmoGames** [comment]
it is giving me this error now

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':processReleaseResources'.
> Could not create task ':mainApkListPersistenceRelease'.
   > org.xml.sax.SAXParseException; systemId: file:/C:/Users/Anthony%20Chen/Desktop/godot%20projects/app/android/build/AndroidManifest.xml; lineNumber: 30; columnNumber: 230; Attribute "replace" bound to namespace "http://schemas.android.com/tools" was already specified for element "application".

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

Exit Code: 1

**Comment by PoqXert** [comment]
You have multiple `tools:replace` attribute, use one.

**Comment by CozmoGames** [comment]
Ok thank you for you help, I just tried to build the apk and it worked.
