### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by KinashMaksym** [PoqXert/godot-appodeal-android-plugin#3]
Hello I have an error when compiling the apk :

**FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:30:68-95
  	is also present at [com.appodeal.ads.sdk:core:2.7.1] AndroidManifest.xml:15:18-44 value=(true).
  	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:30:5-74:19 to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
**

Can you help me please ?

**Comment by PoqXert** [comment]
Add attribute `tools:replace` with value `android:allowBackup` (and other conflicts) to `application` element in `<ProjectFolder>/android/build/AndroidManifest.xml`
```xml
<application tools:replace="android:allowBackup,android:label">
...
</application>
```

**Comment by KinashMaksym** [comment]
Yes. It worked but now the apk doesn't start

**Comment by PoqXert** [comment]
> apk doesn't start

I don't know what you have. Use debugger, fix errors.

**Comment by mpo4apsky** [comment]
> Yes. It worked but now the apk doesn't start

Hi, did you solve this problem, if so how, I faced the same problem.
I will be glad if you help.
