### ISSUE TITLE
Update for 3.3 Stable

### ISSUE THREAD

**Issue by metinUr** [PoqXert/godot-appodeal-android-plugin#4]
In Godot 3.3 stable version plugin cause game crash on startup with this error:
```
AndroidRuntime: FATAL EXCEPTION: main
AndroidRuntime: Process: com.the1311.astrorbit, PID: 28255
AndroidRuntime: java.lang.VerifyError: Verifier rejected class ru.poqxert.godotappodeal.GodotAppodeal: void ru.poqxert.godotappodeal.GodotAppodeal.<init>(org.godotengine.godot.Godot) failed to verify: void ru.poqxert.godotappodeal.GodotAppodeal.<init>(org.godotengine.godot.Godot): [0x6] register v2 has type Reference: org.godotengine.godot.Godot but expected Reference: android.app.Activity (declaration of 'ru.poqxert.godotappodeal.GodotAppodeal' appears in /data/app/~=/com.the1311.astrorbit/base.apk!classes4.dex)
```
same as this issue [java.lang.VerifyError crash on Android app startup when using Android plugin in 3.2.4-rc2 #45983](https://github.com/godotengine/godot/issues/45983) 
this error fixed on admob plugin on [this fork](https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/compare/main...choyg:main) with this change:
```
    public GodotAdMob(Godot godot) {
        super(godot);
 --     activity = godot;
 ++     activity = godot.getActivity();
    }
```
and this is [Update to Godot 3.3](https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/commit/6e98b23e8e59c59b0b919bff85ce15286cfe452e#) commit in admob plugin.

Can you update this plugin to 3.3?
Thanks.

**Comment by PoqXert** [comment]
Thanks for issue.
Plugin updated for 3.3 in v1.0.1

**Comment by metinUr** [comment]
Tested with this new version, and plugin is working again, thank you.
